In [ ]:
import boto3

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
get_it_done = pd.read_csv('get_it_done_2019_requests_datasd.csv')

In [3]:
get_it_done.head()

,service_request_id,requested_datetime,case_age_days,service_name,case_record_type,updated_datetime,status,lat,long,district,case_origin,referred_department,public_description
0,2475207,2019-01-01T00:20:00,NaN,Other,TSW,NaN,Referred,32.710427,-117.145192,8.0,Mobile,Police CRO ? Central,19th and 20th island ave people firing gun sho...
1,2475208,2019-01-01T00:20:00,NaN,Other,TSW,NaN,Referred,32.702298,-117.092751,4.0,Mobile,Police CRO ? Southeastern,Ongoing loud fireworks in area near El Rey Tra...
2,2475209,2019-01-01T00:21:00,15.0,Litter,ESD Complaint/Report,2019-01-15T13:21:00,Closed,32.719797,-117.060215,4.0,Mobile,NaN,3 bags of garbage and one box
3,2475210,2019-01-01T01:06:00,41.0,Street Sweeping,TSW,NaN,In Process,32.702164,-117.051741,4.0,Web,NaN,North side of Skyline Drive from Cielo to Wood...
4,2475211,2019-01-01T01:12:00,18.0,Engineering - Traffic Calming/Safety Features,Traffic Engineering,2019-01-18T15:38:00,Closed,32.829445,-117.279999,1.0,Mobile,NaN,"On December 13, 2018, this delivery truck back..."

In [4]:
get_it_done.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26038 entries, 0 to 26037
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   service_request_id   26038 non-null  int64
 1   requested_datetime   26038 non-null  object
 2   case_age_days        23712 non-null  float64
 3   service_name         25599 non-null  object
 4   case_record_type     26038 non-null  object
 5   updated_datetime     13106 non-null  object
 6   status               26038 non-null  object
 7   lat                  26038 non-null  float64
 8   long                 26038 non-null  float64
 9   district             25748 non-null  float64
 10  case_origin          26017 non-null  object
 11  referred_department  2351 non-null   object
 12  public_description   21726 non-null  object
dtypes: float64(4), int64(1), object(8)
memory usage: 2.6+ MB

In [6]:
get_it_done.tail()

,service_request_id,requested_datetime,case_age_days,service_name,case_record_type,updated_datetime,status,lat,long,district,case_origin,referred_department,public_description
26033,2506640,2019-02-10T13:53:00,0.0,Pothole,TSW,NaN,In Process,32.924886,-117.254572,1.0,Mobile,NaN,Missing asphalt covering concrete half way dow...
26034,2506641,2019-02-10T13:54:00,0.0,Graffiti Removal,TSW,NaN,In Process,32.773308,-117.203812,2.0,Mobile,NaN,NaN
26035,2506642,2019-02-10T13:55:00,0.0,72 Hour Violation,Parking,NaN,In Process,32.760010,-117.139990,3.0,Web,NaN,Stored on street for 2 weeks at same location....
26036,2506643,2019-02-10T13:56:00,0.0,Traffic Signal Timing Issue,TSW,NaN,In Process,32.953704,-117.234141,1.0,Web,NaN,The traffic lights for both eastbound and west...
26037,2506644,2019-02-10T14:01:00,0.0,Illegal Dumping,ESD Complaint/Report,NaN,In Process,32.705742,-117.163094,3.0,Mobile,NaN,A scooter that has seen better days